[2024-04-24T09:35:28.162+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-04-24T09:35:27.365921+00:00 [queued]>
[2024-04-24T09:35:28.167+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-04-24T09:35:27.365921+00:00 [queued]>
[2024-04-24T09:35:28.167+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-24T09:35:28.174+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): download_launches> on 2024-04-24 09:35:27.365921+00:00
[2024-04-24T09:35:28.177+0000] {standard_task_runner.py:60} INFO - Started process 336 to run task
[2024-04-24T09:35:28.179+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'download_launches', 'manual__2024-04-24T09:35:27.365921+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/Example_dag.py', '--cfg-path', '/tmp/tmpgwalr2ta']
[2024-04-24T09:35:28.180+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask download_launches
[2024-04-24T09:35:28.204+0000] {task_command.py:423} INFO - Running <TaskInstance: download_rocket_launches.download_launches manual__2024-04-24T09:35:27.365921+00:00 [running]> on host 99514668da53
[2024-04-24T09:35:28.238+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_rocket_launches' AIRFLOW_CTX_TASK_ID='download_launches' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T09:35:27.365921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-24T09:35:27.365921+00:00'
[2024-04-24T09:35:28.239+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-24T09:35:28.239+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "curl -o /launches.json -L 'https://ll.thespacedevs.com/2.0.0/launch/upcoming'"]
[2024-04-24T09:35:28.244+0000] {subprocess.py:86} INFO - Output:
[2024-04-24T09:35:28.249+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-04-24T09:35:28.249+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-04-24T09:35:29.530+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[2024-04-24T09:35:31.399+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0Warning: Failed to open the file /launches.json: Permission denied
[2024-04-24T09:35:31.400+0000] {subprocess.py:93} INFO -   5 25873    5  1360    0     0    431      0  0:01:00  0:00:03  0:00:57  1565
[2024-04-24T09:35:31.400+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2024-04-24T09:35:31.401+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2024-04-24T09:35:31.407+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2024-04-24T09:35:31.408+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=download_launches, execution_date=20240424T093527, start_date=20240424T093528, end_date=20240424T093531
[2024-04-24T09:35:31.415+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task download_launches (Bash command failed. The command returned a non-zero exit code 23.; 336)
[2024-04-24T09:35:31.439+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-24T09:35:31.451+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
